name: Trigger auto deployment for containerapp gabc2022

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gabc2022-AutoDeployTrigger-0716cd9a-2e81-4b43-b5e5-7b0354b4c8a2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: gabc2022.azurecr.io
          username: ${{ secrets.GABC2022_REGISTRY_USERNAME }}
          password: ${{ secrets.GABC2022_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gabc2022.azurecr.io/gabc2022:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GABC2022_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n gabc2022 -g SampleGroup --server gabc2022.azurecr.io --username  ${{ secrets.GABC2022_REGISTRY_USERNAME }} --password ${{ secrets.GABC2022_REGISTRY_PASSWORD }}
            az containerapp update -n gabc2022 -g SampleGroup --image gabc2022.azurecr.io/gabc2022:${{ github.sha }}
